/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grepolis.tester;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApplicationTest {
    @Test void instanceIsNotNull() {
        Application app = new Application();
        assertNotNull(app);
    }
}
